# We can't leave this up to geerlingguy.jenkins until
# https://github.com/geerlingguy/ansible-role-jenkins/issues/50 is resolved.
---
- name: Install Jenkins plugins.
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: "{{ solita_jenkins_plugins_required + solita_jenkins_plugins }}"
  register: plugins

- include: restart.yml
  when: plugins | changed
